// scanning
export const START_DEVICE_SCAN = 'START_DEVICE_SCAN';
export const STOP_DEVICE_SCAN = 'STOP_DEVICE_SCAN';
export const FOUND_DEVICE = 'FOUND_DEVICE';
export const CONNECT_DEVICE = 'CONNECT_DEVICE';
export const RECONNECT_DEVICE = 'RECONNECT_DEVICE';
export const STOP_RECONNECT = 'STOP_RECONNECT';

// connection status
export const BLUETOOTH_OFF = 'BLUETOOTH_OFF';
export const DISCONNECTED_FROM_DEVICE = 'DISCONNECTED_FROM_DEVICE';
export const CONNECTING_TO_DEVICE = 'CONNECTING_TO_DEVICE';
export const CONNECTED_TO_DEVICE = 'CONNECTED_TO_DEVICE';
export const RECONNECTING_TO_DEVICE = 'RECONNECTING_TO_DEVICE';

// connected
export const ADD_REP_DATA = 'ADD_REP_DATA';
export const DISCONNECT_DEVICE = 'DISCONNECT_DEVICE';

// auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SAVE_TOKENS = 'SAVE_TOKENS';
export const TOKENS_READY = 'TOKENS_READY';

// sets
export const SAVE_WORKOUT_SET = 'SAVE_WORKOUT_SET';
export const SAVE_WORKOUT_SET_TAGS = 'SAVE_WORKOUT_SET_TAGS';
export const SAVE_HISTORY_SET = 'SAVE_HISTORY_SET';
export const SAVE_HISTORY_SET_TAGS = 'SAVE_HISTORY_SET_TAGS';
export const SAVE_WORKOUT_REP = 'SAVE_WORKOUT_REP';
export const SAVE_HISTORY_REP = 'SAVE_HISTORY_REP';
export const END_SET = 'END_SET';
export const DELETE_WORKOUT_VIDEO = 'DELETE_WORKOUT_VIDEO';
export const DELETE_HISTORY_VIDEO = 'DELETE_HISTORY_VIDEO';
export const LOAD_PERSISTED_SET_DATA = 'LOAD_PERSISTED_SET_DATA';
export const END_WORKOUT = 'END_WORKOUT';
export const BEGIN_UPLOADING_SETS = 'BEGIN_UPLOADING_SETS';
export const UPDATE_SET_DATA_FROM_SERVER = 'UPDATE_SET_DATA_FROM_SERVER';
export const FINISH_UPLOADING_SETS = 'FINISH_UPLOADING_SETS';
export const FAILED_UPLOAD_SETS = 'FAILED_UPLOAD_SETS';

// timer
export const PAUSE_END_SET_TIMER = 'PAUSE_END_SET_TIMER';
export const RESUME_END_SET_TIMER = 'RESUME_END_SET_TIMER';
export const START_END_SET_TIMER = 'START_END_SET_TIMER';
export const STOP_END_SET_TIMER = 'STOP_END_SET_TIMER';

// store
export const STORE_INITIALIZED = 'STORE_INITIALIZED';

// tab
export const CHANGED_TAB = 'CHANGED_TAB';

// suggestions
export const UPDATE_SUGGESTIONS = 'UPDATE_SUGGESTIONS';

// workout
export const PRESENT_WORKOUT_EXERCISE = 'PRESENT_WORKOUT_EXERCISE';
export const PRESENT_WORKOUT_TAGS = 'PRESENT_WORKOUT_TAGS';
export const PRESENT_WORKOUT_EXPANDED = 'PRESENT_WORKOUT_EXPANDED';
export const START_EDITING_WORKOUT_RPE = 'START_EDITING_WORKOUT_RPE';
export const START_EDITING_WORKOUT_WEIGHT = 'START_EDITING_WORKOUT_WEIGHT';
export const DISMISS_WORKOUT_EXERCISE = 'DISMISS_WORKOUT_EXERCISE';
export const DISMISS_WORKOUT_TAGS = 'DISMISS_WORKOUT_TAGS';
export const DISMISS_WORKOUT_EXPANDED = 'DISMISS_WORKOUT_EXPANDED';
export const END_EDITING_WORKOUT_RPE = 'END_EDITING_WORKOUT_RPE';
export const END_EDITING_WORKOUT_WEIGHT = 'END_EDITING_WORKOUT_WEIGHT';
export const PRESENT_WORKOUT_VIDEO_RECORDER = 'PRESENT_WORKOUT_VIDEO_RECORDER';
export const PRESENT_WORKOUT_VIDEO_PLAYER = 'PRESENT_WORKOUT_VIDEO_PLAYER';
export const DISMISS_WORKOUT_VIDEO_RECORDER = 'DISMISS_WORKOUT_VIDEO_RECORDER';
export const DISMISS_WORKOUT_VIDEO_PLAYER = 'DISMISS_WORKOUT_VIDEO_PLAYER';
export const START_RECORDING_WORKOUT = 'START_RECORDING_WORKOUT';
export const STOP_RECORDING_WORKOUT = 'STOP_RECORDING_WORKOUT';
export const SAVE_WORKOUT_VIDEO = 'SAVE_WORKOUT_VIDEO';

// history
export const UPDATE_HISTORY_FILTER = 'UPDATE_HISTORY_FILTER';
export const EXPORTING_CSV = 'EXPORTING_CSV';
export const LOADING_HISTORY = 'LOADING_HISTORY';
export const PRESENT_HISTORY_EXERCISE = 'PRESENT_HISTORY_EXERCISE';
export const PRESENT_HISTORY_TAGS = 'PRESENT_HISTORY_TAGS';
export const PRESENT_HISTORY_EXPANDED = 'PRESENT_HISTORY_EXPANDED';
export const START_EDITING_HISTORY_RPE = 'START_EDITING_HISTORY_RPE';
export const START_EDITING_HISTORY_WEIGHT = 'START_EDITING_HISTORY_WEIGHT';
export const DISMISS_HISTORY_EXERCISE = 'DISMISS_HISTORY_EXERCISE';
export const DISMISS_HISTORY_TAGS = 'DISMISS_HISTORY_TAGS';
export const DISMISS_HISTORY_EXPANDED = 'DISMISS_HISTORY_EXPANDED';
export const END_EDITING_HISTORY_RPE = 'END_EDITING_HISTORY_RPE';
export const END_EDITING_HISTORY_WEIGHT = 'END_EDITING_HISTORY_WEIGHT';
export const PRESENT_HISTORY_VIDEO_RECORDER = 'PRESENT_HISTORY_VIDEO_RECORDER';
export const PRESENT_HISTORY_VIDEO_PLAYER = 'PRESENT_HISTORY_VIDEO_PLAYER';
export const DISMISS_HISTORY_VIDEO_RECORDER = 'DISMISS_HISTORY_VIDEO_RECORDER';
export const DISMISS_HISTORY_VIDEO_PLAYER = 'DISMISS_HISTORY_VIDEO_PLAYER';
export const START_RECORDING_HISTORY = 'START_RECORDING_HISTORY';
export const STOP_RECORDING_HISTORY = 'STOP_RECORDING_HISTORY';
export const SAVE_HISTORY_VIDEO = 'SAVE_HISTORY_VIDEO';

// settings
export const SAVE_END_SET_TIMER = 'SAVE_END_SET_TIMER';
export const PRESENT_END_SET_TIMER = 'PRESENT_END_SET_TIMER';
export const DISMISS_END_SET_TIMER = 'DISMISS_END_SET_TIMER';
export const SAVE_DEFAULT_METRIC = 'SAVE_DEFAULT_METRIC';
export const PRESENT_DEFAULT_METRIC = 'PRESENT_DEFAULT_METRIC';
export const DISMISS_DEFAULT_METRIC = 'DISMISS_DEFAULT_METRIC';
export const UPDATE_SYNC_DATE = 'UPDATE_SYNC_DATE';

// app state
export const UNLOCKED_SCREEN = 'UNLOCKED_SCREEN';
export const LOCKED_SCREEN = 'LOCKED_SCREEN';

// kill switch
export const FETCH_VERSION = 'FETCH_VERSION';
export const VERSION_OK = 'VERSION_OK';
export const VERSION_KILLED = 'VERSION_KILLED';
export const VERSION_UNAVAILABLE = 'VERSION_UNAVAILABLE';