# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OBBApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OBBApp
  pod 'Firebase', '4.4.0'
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  target 'OBBAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'OBBApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OBBApp-tvOS

  target 'OBBApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
