# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OBBApp' do
  # Do not use use_frameworks!, instead Swift packages should go through Carthage

  # Pods for OBBApp
  pod 'Firebase', '4.8.0'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
  pod 'Fabric', '1.7.2'
  pod 'Crashlytics', '3.9.3'
  pod 'GoogleIDFASupport', '3.14.0'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  target 'OBBAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'OBBApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OBBApp-tvOS

  target 'OBBApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
